
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 11 23:00:15 CDT 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbol {
  /* terminals */
  public static final int SCANF = 31;
  public static final int GE = 10;
  public static final int PERIOD = 3;
  public static final int INTEGER = 39;
  public static final int LPAREN = 16;
  public static final int INT = 29;
  public static final int PRINTLN = 33;
  public static final int FOR = 32;
  public static final int MINUS = 19;
  public static final int REF = 15;
  public static final int D = 38;
  public static final int RPAREN = 17;
  public static final int SEMICOLON = 2;
  public static final int LT = 7;
  public static final int FTM2 = 37;
  public static final int OR = 14;
  public static final int COMMA = 4;
  public static final int PLUS = 18;
  public static final int QUOTE = 41;
  public static final int IF = 35;
  public static final int ASSIGN = 11;
  public static final int MAIN = 25;
  public static final int ID = 40;
  public static final int LE = 8;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int error = 1;
  public static final int EQ = 12;
  public static final int LBRACK = 22;
  public static final int IMPORT = 26;
  public static final int TIMES = 20;
  public static final int NQ = 13;
  public static final int ELSE = 36;
  public static final int LBRACE = 5;
  public static final int FUNC = 27;
  public static final int RBRACK = 23;
  public static final int PACKAGE = 24;
  public static final int RBRACE = 6;
  public static final int DIVID = 21;
  public static final int FMT = 30;
  public static final int GT = 9;
  public static final int VAR = 28;
}

